### ISSUE TITLE
Fix simple wires error with 6 wires

### ISSUE THREAD

**Issue by JulianNorton** [MartinHarding/ktaned#24]
```
Enter wire colors: black blue blue white white black
Traceback (most recent call last):
  File "cli-example.py", line 106, in <module>
    solve_wires()
  File "cli-example.py", line 22, in solve_wires
    solution = wires.solve()
  File "/Users/j/github/ktaned/ktaned/simple_wires.py", line 62, in solve
    if 'yellow' not in self.wires and int(bomb.serial[-1]) % 2:
NameError: name 'bomb' is not defined
```

**Comment by MartinHarding** [comment]
Closed by #26
