### ISSUE TITLE
The Button errors on set strip light color

### ISSUE THREAD

**Issue by JulianNorton** [MartinHarding/ktaned#25]
```
Enter module [w,b,m]: b
Batteries: 2
FRK indicator? [y/n]: y
CAR indicator? [y/n]: n
Button color: blue
Button label: abort
Hold the button
Light strip color: white
Traceback (most recent call last):
  File "cli-example.py", line 108, in <module>
    solve_button()
  File "cli-example.py", line 59, in solve_button
    button.set_strip_light_color(light_strip_color)
AttributeError: 'Button' object has no attribute 'set_strip_light_color'
```

**Comment by MartinHarding** [comment]
Closed by 25bebcc
